    vim.map("0", "<0>", "TTOTAL_CMD")
    vim.map("1", "<1>", "TTOTAL_CMD")
    vim.map("2", "<2>", "TTOTAL_CMD")
    vim.map("3", "<3>", "TTOTAL_CMD")
    vim.map("4", "<4>", "TTOTAL_CMD")
    vim.map("5", "<5>", "TTOTAL_CMD")
    vim.map("6", "<6>", "TTOTAL_CMD")
    vim.map("7", "<7>", "TTOTAL_CMD")
    vim.map("8", "<8>", "TTOTAL_CMD")
    vim.map("9", "<9>", "TTOTAL_CMD")
    ;~ vim.map("a", "<cm_SelectAll>", "TTOTAL_CMD")
    vim.map("b", "<cm_CompareFilesByContent>", "TTOTAL_CMD")
    vim.map("B", "<cm_IntCompareFilesByContent>", "TTOTAL_CMD")
    vim.map("c", "<TC_CopyUseQueues>", "TTOTAL_CMD")
    vim.map("C", "<TC_FileCopyForBak>", "TTOTAL_CMD")
    ;~ vim.map("d", "<cm_DirectoryHotlist>", "TTOTAL_CMD")
    ;~ vim.map("D", "<cm_OpenDesktop>", "TTOTAL_CMD")
    ;~ vim.map("e", "<cm_ContextMenu>", "TTOTAL_CMD")
    ;~ vim.map("E", "<cm_ExeCuteDOS>", "TTOTAL_CMD")
    vim.map("n", "<cm_OpenNewTab>", "TTOTAL_CMD")
    ;~ vim.map("N", "<TC_azHistory>", "TTOTAL_CMD")
    vim.map("m", "<cm_DirectoryHistory>", "TTOTAL_CMD")
    ;~ vim.map("M", "<TC_Half>", "TTOTAL_CMD")
    vim.map("u", "<TC_GoToParentEx>", "TTOTAL_CMD")
    vim.map("U", "<cm_GoToRoot>", "TTOTAL_CMD")
    vim.map("o", "<cm_MkDir>", "TTOTAL_CMD")
    ;~ vim.map("o", "<cm_LeftOpenDrives>", "TTOTAL_CMD")
    vim.map("O", "<TC_MkDirPasteFile>", "TTOTAL_CMD")
    vim.map("q", "<cm_SrcQuickView>", "TTOTAL_CMD")
    vim.map("Q", "<cm_List>", "TTOTAL_CMD")
    vim.map("r", "<cm_RenameOnly>", "TTOTAL_CMD")
    vim.map("R", "<cm_MultiRenameFiles>", "TTOTAL_CMD")
    vim.map("x", "<cm_edit>", "TTOTAL_CMD")
    ;~ vim.map("x", "<cm_Delete>", "TTOTAL_CMD")
    vim.map("X", "<TC_ForceDelete>", "TTOTAL_CMD")
    ;~ vim.map("w", "<cm_edit>", "TTOTAL_CMD")
    vim.map("y", "<cm_CopyNamesToClip>", "TTOTAL_CMD")
    vim.map("Y", "<cm_CopyFullNamesToClip>", "TTOTAL_CMD")
    vim.map("P", "<cm_PackFiles>", "TTOTAL_CMD")
    vim.map("p", "<cm_UnpackFiles>", "TTOTAL_CMD")
    vim.map("t", "<cm_ContextMenu>", "TTOTAL_CMD")
    vim.map("T", "<TC_TwoFileExchangeName>", "TTOTAL_CMD")
    vim.map("/", "<cm_ShowQuickSearch>", "TTOTAL_CMD")
    vim.map("?", "<cm_SearchFor>", "TTOTAL_CMD")
    vim.map("[", "<cm_SelectCurrentName>", "TTOTAL_CMD")
    vim.map("{", "<cm_UnselectCurrentName>", "TTOTAL_CMD")
    vim.map("]", "<cm_SelectCurrentExtension>", "TTOTAL_CMD")
    vim.map("}", "<cm_UnSelectCurrentExtension>", "TTOTAL_CMD")
    vim.map("\", "<cm_ExchangeSelection>", "TTOTAL_CMD")
    vim.map("|", "<cm_ClearAll>", "TTOTAL_CMD")
    vim.map("-", "<cm_SwitchSeparateTree>", "TTOTAL_CMD")
    vim.map("=", "<cm_MatchSrc>", "TTOTAL_CMD")
    vim.map(",", "<cm_SrcThumbs>", "TTOTAL_CMD")
    vim.map(".", "<TC_CmdHistory>", "TTOTAL_CMD")
    vim.map(":", "<cm_List>", "TTOTAL_CMD")
    vim.map(";", "<cm_SrcQuickView>", "TTOTAL_CMD")
	vim.map("'", "<cm_EditPath>", "TTOTAL_CMD")
	vim.map("""", "<cm_FocusCmdLine>", "TTOTAL_CMD")
    vim.map("~", "<cm_SysInfo>", "TTOTAL_CMD")
    ;~ vim.map("``", "<cm_ShowQuickSearch>", "TTOTAL_CMD")
	;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	vim.map("e", "<up>", "TTOTAL_CMD")
    vim.map("E", "<cm_SwitchToNextTab>", "TTOTAL_CMD")
	vim.map("d", "<down>", "TTOTAL_CMD")
	vim.map("D", "<cm_SwitchToPreviousTab>", "TTOTAL_CMD")
    vim.map("s", "<left>", "TTOTAL_CMD")
    vim.map("S", "<cm_GotoPreviousDir>", "TTOTAL_CMD")
    vim.map("f", "<right>", "TTOTAL_CMD")
	vim.map("F", "<cm_GotoNextDir>", "TTOTAL_CMD")
	vim.map("z", "<cm_DirectoryHotlist>", "TTOTAL_CMD")
    vim.map("Z", "<cm_SrcThumbs>", "TTOTAL_CMD")
	vim.map("w", "<TC_GoToParentEx>", "TTOTAL_CMD")
    vim.map("W", "<cm_GoToRoot>", "TTOTAL_CMD")
	;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	vim.map("k", "<up>", "TTOTAL_CMD")
    vim.map("K", "<cm_SwitchToNextTab>", "TTOTAL_CMD")
    ;~ vim.map("K", "<TC_UpSelect>", "TTOTAL_CMD")
    vim.map("j", "<down>", "TTOTAL_CMD")
    vim.map("J", "<cm_SwitchToPreviousTab>", "TTOTAL_CMD")
    ;~ vim.map("J", "<TC_DownSelect>", "TTOTAL_CMD")
    vim.map("h", "<left>", "TTOTAL_CMD")
    vim.map("H", "<cm_GotoPreviousDir>", "TTOTAL_CMD")
    vim.map("l", "<right>", "TTOTAL_CMD")
    vim.map("L", "<cm_GotoNextDir>", "TTOTAL_CMD")
    vim.map("i", "<TC_InsertMode>", "TTOTAL_CMD")
    vim.map("I", "<TC_ToggleShowInfo>", "TTOTAL_CMD")
	;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	;复制/移动到右侧 f取file的意思 filecopy
    ;~ vim.map("fc", "<cm_CopyOtherpanel>", "TTOTAL_CMD")
    ;~ vim.map("fx", "<cm_MoveOnly>", "TTOTAL_CMD")
    ;ff复制到剪切板 fz剪切到剪切板 fv粘贴
    ;~ vim.map("ff", "<cm_CopyToClipboard>", "TTOTAL_CMD")
    ;~ vim.map("fz", "<cm_CutToClipboard>", "TTOTAL_CMD")
    ;~ vim.map("fv", "<cm_PasteFromClipboard>", "TTOTAL_CMD")
    ;使用队列复制/移动到右侧 q-queue, fcq会影响对fc的使用，改用fqc/fqx的方式
    ;~ vim.map("fqc", "<TC_CopyUseQueues>", "TTOTAL_CMD")
    ;~ vim.map("fqx", "<TC_MoveUseQueues>", "TTOTAL_CMD")
    ;fb复制到收藏夹某个目录，fd移动到收藏夹的某个目录
    ;~ vim.map("fb", "<TC_CopyDirectoryHotlist>", "TTOTAL_CMD")
    ;~ vim.map("fd", "<TC_MoveDirectoryHotlist>", "TTOTAL_CMD")
    ;~ vim.map("fg", "<cm_CopySrcPathToClip>", "TTOTAL_CMD")
    ;~ vim.map("ft", "<cm_SyncChangeDir>", "TTOTAL_CMD")
    ;~ vim.map("F", "<TC_SearchMode>", "TTOTAL_CMD")
	;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    vim.map("G", "<TC_LastLine>", "TTOTAL_CMD")
    vim.map("ga", "<cm_CloseAllTabs>", "TTOTAL_CMD")
    vim.map("gg", "<TC_GoToLine>", "TTOTAL_CMD")
    vim.map("g$", "<TC_LastLine>", "TTOTAL_CMD")
    vim.map("gt", "<cm_SwitchToNextTab>", "TTOTAL_CMD")
    vim.map("gT", "<cm_SwitchToPreviousTab>", "TTOTAL_CMD")
    vim.map("gc", "<cm_CloseCurrentTab>", "TTOTAL_CMD")
    vim.map("gb", "<cm_OpenDirInNewTabOther>", "TTOTAL_CMD")
    vim.map("ge", "<cm_Exchange>", "TTOTAL_CMD")
    vim.map("gr", "<TC_ReOpenTab>", "TTOTAL_CMD")
    vim.map("gw", "<cm_ExchangeWithTabs>", "TTOTAL_CMD")
	;~ vim.map("gh", "<TC_GotoPreviousDirOther>", "TTOTAL_CMD")
    ;~ vim.map("gl", "<TC_GotoNextDirOther>", "TTOTAL_CMD")
    vim.map("g1", "<cm_SrcActivateTab1>", "TTOTAL_CMD")
    vim.map("g2", "<cm_SrcActivateTab2>", "TTOTAL_CMD")
    vim.map("g3", "<cm_SrcActivateTab3>", "TTOTAL_CMD")
    vim.map("g4", "<cm_SrcActivateTab4>", "TTOTAL_CMD")
    vim.map("g5", "<cm_SrcActivateTab5>", "TTOTAL_CMD")
    ;~ vim.map("g6", "<cm_SrcActivateTab6>", "TTOTAL_CMD")
    ;~ vim.map("g7", "<cm_SrcActivateTab7>", "TTOTAL_CMD")
    ;~ vim.map("g8", "<cm_SrcActivateTab8>", "TTOTAL_CMD")
    ;~ vim.map("g9", "<cm_SrcActivateTab9>", "TTOTAL_CMD")
    ;~ vim.map("g0", "<TC_GoLastTab>", "TTOTAL_CMD")
	;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	vim.map("af", "<cm_SrcByName>", "TTOTAL_CMD")
    vim.map("ae", "<cm_SrcByExt>", "TTOTAL_CMD")
    vim.map("as", "<cm_SrcBySize>", "TTOTAL_CMD")
    vim.map("ad", "<cm_SrcByDateTime>", "TTOTAL_CMD")
    vim.map("ar", "<cm_SrcNegOrder>", "TTOTAL_CMD")
    vim.map("a1", "<cm_SrcSortByCol1>", "TTOTAL_CMD")
    vim.map("a2", "<cm_SrcSortByCol2>", "TTOTAL_CMD")
    vim.map("a3", "<cm_SrcSortByCol3>", "TTOTAL_CMD")
    vim.map("a4", "<cm_SrcSortByCol4>", "TTOTAL_CMD")
    vim.map("a5", "<cm_SrcSortByCol5>", "TTOTAL_CMD")
    vim.map("A", "<TC_CreateNewFile>", "TTOTAL_CMD")
    ;~ vim.map("sf", "<cm_SrcByName>", "TTOTAL_CMD")
    ;~ vim.map("se", "<cm_SrcByExt>", "TTOTAL_CMD")
    ;~ vim.map("ss", "<cm_SrcBySize>", "TTOTAL_CMD")
    ;~ vim.map("sd", "<cm_SrcByDateTime>", "TTOTAL_CMD")
    ;~ vim.map("sr", "<cm_SrcNegOrder>", "TTOTAL_CMD")
    ;~ vim.map("s1", "<cm_SrcSortByCol1>", "TTOTAL_CMD")
    ;~ vim.map("s2", "<cm_SrcSortByCol2>", "TTOTAL_CMD")
    ;~ vim.map("s3", "<cm_SrcSortByCol3>", "TTOTAL_CMD")
    ;~ vim.map("s4", "<cm_SrcSortByCol4>", "TTOTAL_CMD")
    ;~ vim.map("s5", "<cm_SrcSortByCol5>", "TTOTAL_CMD")
    ;~ vim.map("s6", "<cm_SrcSortByCol6>", "TTOTAL_CMD")
    ;~ vim.map("s7", "<cm_SrcSortByCol7>", "TTOTAL_CMD")
    ;~ vim.map("s8", "<cm_SrcSortByCol8>", "TTOTAL_CMD")
    ;~ vim.map("s9", "<cm_SrcSortByCol9>", "TTOTAL_CMD")
    ;~ vim.map("s0", "<cm_SrcUnsorted>", "TTOTAL_CMD")
    ;~ vim.map("S", "<TC_SameFiles>", "TTOTAL_CMD")
	;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ;~ vim.map("v", "<cm_SrcCustomViewMenu>", "TTOTAL_CMD")
    vim.map("v", "<TC_MoveUseQueues>", "TTOTAL_CMD")
    vim.map("V", "<TC_SameFiles>", "TTOTAL_CMD")
    ;~ vim.map("Vb", "<cm_VisButtonbar>", "TTOTAL_CMD")
    ;~ vim.map("Vc", "<cm_VisDriveCombo>", "TTOTAL_CMD")
    ;~ vim.map("Vd", "<cm_VisDriveButtons>", "TTOTAL_CMD")
    ;~ vim.map("Ve", "<cm_CommandBrowser>", "TTOTAL_CMD")
    ;~ vim.map("Vf", "<cm_VisKeyButtons>", "TTOTAL_CMD")
    ;~ vim.map("Vh", "<cm_SwitchIgnoreList>", "TTOTAL_CMD")
    ;~ vim.map("Vm", "<TC_ToggleMenu>", "TTOTAL_CMD")
    ;~ vim.map("Vn", "<cm_VisCmdLine>", "TTOTAL_CMD")
    ;~ vim.map("Vo", "<cm_VisTwoDriveButtons>", "TTOTAL_CMD")
    ;~ vim.map("Vr", "<cm_VisDriveCombo>", "TTOTAL_CMD")
    ;~ vim.map("Vs", "<cm_VisStatusbar>", "TTOTAL_CMD")
    ;~ vim.map("Vt", "<cm_VisTabHeader>", "TTOTAL_CMD")
    ;~ vim.map("Vw", "<cm_VisDirTabs>", "TTOTAL_CMD")
	vim.map(",b", "<cm_VisButtonbar>", "TTOTAL_CMD")
    vim.map(",c", "<cm_VisDriveCombo>", "TTOTAL_CMD")
    vim.map(",d", "<cm_VisDriveButtons>", "TTOTAL_CMD")
    vim.map(",e", "<cm_CommandBrowser>", "TTOTAL_CMD")
    vim.map(",f", "<cm_VisKeyButtons>", "TTOTAL_CMD")
    vim.map(",h", "<cm_SwitchIgnoreList>", "TTOTAL_CMD")
    vim.map(",m", "<TC_ToggleMenu>", "TTOTAL_CMD")
    vim.map(",n", "<cm_VisCmdLine>", "TTOTAL_CMD")
    vim.map(",o", "<cm_VisTwoDriveButtons>", "TTOTAL_CMD")
    vim.map(",r", "<cm_VisDriveCombo>", "TTOTAL_CMD")
    vim.map(",s", "<cm_VisStatusbar>", "TTOTAL_CMD")
    vim.map(",t", "<cm_VisTabHeader>", "TTOTAL_CMD")
    vim.map(",w", "<cm_VisDirTabs>", "TTOTAL_CMD")
	;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ;~ vim.map("zz", "<TC_Toggle_50_100Percent>", "TTOTAL_CMD")
    ;~ vim.map("zh", "<TC_Toggle_50_100Percent_V>", "TTOTAL_CMD")
    ;~ vim.map("zi", "<TC_WinMaxLeft>", "TTOTAL_CMD")
    ;~ vim.map("zo", "<TC_WinMaxRight>", "TTOTAL_CMD")
    ;~ vim.map("zt", "<TC_AlwayOnTop>", "TTOTAL_CMD")
    ;~ vim.map("zn", "<cm_Minimize>", "TTOTAL_CMD")
    ;~ vim.map("zm", "<cm_Maximize>", "TTOTAL_CMD")
    ;~ vim.map("zr", "<cm_Restore>", "TTOTAL_CMD")
    ;~ vim.map("zv", "<cm_VerticalPanels>", "TTOTAL_CMD")
    ;~ vim.map("Z", "<TC_ToggleMenu>", "TTOTAL_CMD")
	vim.map(".z", "<cm_50Percent>", "TTOTAL_CMD")
    vim.map(".h", "<TC_Toggle_50_100Percent_V>", "TTOTAL_CMD")
    vim.map(".i", "<TC_WinMaxLeft>", "TTOTAL_CMD")
    vim.map(".o", "<TC_WinMaxRight>", "TTOTAL_CMD")
    vim.map(".t", "<TC_AlwayOnTop>", "TTOTAL_CMD")
    vim.map(".n", "<cm_Minimize>", "TTOTAL_CMD")
    vim.map(".m", "<cm_Maximize>", "TTOTAL_CMD")
    vim.map(".r", "<cm_Restore>", "TTOTAL_CMD")
    vim.map(".v", "<cm_VerticalPanels>", "TTOTAL_CMD")